- Name : Muhammad Irgi Faj'ri
- NPM : 221106042881
- dataset : melb_housing.csv
- overview :

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# read csv file from your drive
url = 'drive/MyDrive/dataset/melb_data.csv'
data = pd.read_csv(url)

# show head of the dataset (upper 5 rows in dataset)
data.head()

# # handle categorical data with one-hot encoding
data = pd.get_dummies(data, drop_first=True)

# splitting to feature and target
X = data[['Lattitude', 'Longtitude']] # feature
y = data['Price'] # target

# split data to train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# create Decision Tree model
model = DecisionTreeRegressor(random_state=42)

# train model on training data
model.fit(X_train, y_train)

# make predictions on test data
y_pred = model.predict(X_test)

In [ ]:
# Validation Time

# 1. prepare data

# X real necessary columns
test_value = data[['Lattitude', 'Longtitude']]

# Real prices
y_actual = data['Price'].values

# predicted value
y_predicted = model.predict(test_value)

# y_predicted as a list:
y_predicted = y_predicted.tolist()

# 2, using MAE
import numpy as np

def mean_absolute_error(y_actual, y_predicted):
    basket = []
    for i in range(len(y_actual)):
        selisih = np.abs(y_actual[i] - y_predicted[i])
        basket.append(selisih)
    mae = np.mean(basket)
    return mae

# Example usage
y_act = np.array(y_actual)
y_pred = np.array(y_predicted)

mae = mean_absolute_error(y_act, y_pred)
print(f"Mean Absolute Error: {mae}")

Mean Absolute Error: 83597.0009461329

In [ ]:
data.head()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,...,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,2,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,...,False,True,False,False,True,False,False,False,False,False
1,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,...,False,True,False,False,True,False,False,False,False,False
2,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,...,False,True,False,False,True,False,False,False,False,False
3,3,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,...,False,True,False,False,True,False,False,False,False,False
4,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,...,False,True,False,False,True,False,False,False,False,False